params:
  color: teal  # Any color in CSS syntax
  width: 42rem  # Any length in CSS syntax
  footer: Except where otherwise noted, content on this site is licensed under
    a <a href="http://creativecommons.org/licenses/by/4.0/" rel="license">
    Creative Commons Attribution 4.0 International License</a>.
  rss: To subscribe to this RSS feed, copy its address and paste it into your
    favorite feed reader.

title: TypeSnacks
theme: codelabs

outputs:
  page : 
    - html
    - json
  home: 
    - html
    - json
  courses: 
    - html
    - json
  section:
    - html
    - json
  taxonomy: 
    - json
menu:
  nav:
  - name: Snacks
    url: snacks/
    weight: 1
  - name: Tutorials
    url: tutorials/
    weight: 2
  - name: Courses 
    url: courses/
    weight: 3